### ISSUE TITLE
Question about scheduler and controller-manager binding

### ISSUE THREAD

**Issue by WilliamCocker** [githubixx/ansible-role-kubernetes-controller#8]
So as you might have guessed, I'm facing [this problem](https://github.com/kubernetes/kubernetes/issues/27607).

![screen shot 2018-05-14 at 17 25 32](https://user-images.githubusercontent.com/37018962/40007068-296aaf5c-579c-11e8-9067-0a765594f513.png)

What if I care about not binding my cluster on all interfaces? Is this only a kubectl status display issue or will this prevent nominal operations going further?

FYI, I have installed k8s v1.9.7 (didn't want to deviate too much from the versions in the tutorials). I'll try the 1.10.x branch later while trying to update my cluster. So I don't know if the problem is fixed in v1.10.x but I guess not since it is still opened.

Thanks again for all the great work and documentation.

**Comment by githubixx** [comment]
I guess this problem will never get fixed as nobody cares about and the issue does not get any attention by other users. Basically you can bind all K8s services to all interfaces. That's not a problem in general. It's a security thingy. My concern was to open services to the internet accidentally. So by binding all K8s services to the PeerVPN interfaces has the advantage that all K8s service communication is encrypted by default and as it is a private network it's not reachable from the outside. So in case the firewall is down by accident e.g. it's still not possible to reach any K8s service. My first intention was to be able to run the whole setup without any firewall but later found out that I need to block requests at least for the Traefik dashboard on port 8080.
So if you want to bind on all interfaces it's perfectly possible. But be aware that you then need to protect the services by a firewall. Additionally also routing may not work as expected anymore. Maybe packets travel a different (unsecure) route then. Having all K8s services bound to PeerVPN interfaces there are not much options for routing ;-)

**Comment by WilliamCocker** [comment]
I do care a lot about security, this is why I ask. So if I leave it as it is, will the cluster work properly even if kubectl reports an unhealthy status? My endgame is to use this on public cloud instances so avoiding accidental internet exposure is definitely something I want...

**Comment by githubixx** [comment]
That's the output of my cluster:
```
kubectl get componentstatus 
NAME                 STATUS      MESSAGE                                                                                        ERROR
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: getsockopt: connection refused   
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: getsockopt: connection refused   
etcd-2               Healthy     {"health": "true"}                                                                             
etcd-1               Healthy     {"health": "true"}                                                                             
etcd-0               Healthy     {"health": "true"}
```
Besides that `kubectl` tells me that the `scheduler` and `controller-manger` refusing connection the whole cluster works fine. According to the K8s issue the problem is really only that the test connects to `127.0.0.1` and this is hard coded. And since both only listen on the PeerVPN interface (in my case) there is no service on localhost... But if this command 

```
netstat -ltpn | grep -E '102[0-9]{2}'
tcp        0      0 10.3.0.201:10251        0.0.0.0:*               LISTEN      12541/kube-schedule
tcp        0      0 10.3.0.201:10252        0.0.0.0:*               LISTEN      11296/kube-controll
```
on the K8s controller nodes shows the output above the services should be in good shape (which can also be verified by having a look at the logs of the services with `journalctl`).

**Comment by WilliamCocker** [comment]
Ok thanks for the clarification. I saw the netstat and journalctl checks in your blogpost (and everything seems fine) but I wanted to be sure there wasn't another process depending on kubectl reporting a healthy status for everything to run smoothly.
